cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path(r'^orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('', include(('shop.urls',  'shop'), namespace='shop')),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    url(r'^products/$', views.allproduct, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
    url(r'^$', views.mpage, name='mainpage'),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                        args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    image2 = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    image3 = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)


    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_detail',
                        args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm


def mpage(request):
    print(request.path)
    
    return render(request, 'shop/product/list.html')

def allproduct(request, category_slug=None):
    print(request.path)
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/mainlist.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    print(request.path)
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', {'product': product,
                                                        'cart_product_form': cart_product_form})


def product_list(request, category_slug=None):
    print(request.path)
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/mainlist.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
<div class="container">
    <div class="product-detail pd d-flex ">
        <div class="datail d-flex justify-content-between">
            <div id="big" class="сol-xl-10 col-10 col-md-10 col-10 col-sm-10 col-10 col-lg-10 col-8">
                <img class="mainImg" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
            </div>
     
            <div class="leftDetail  сol-xl-2 col-md-2 col-sm-2 col-lg-2 col-4 d-flex flex-column" id="small">
                <a href="{% if product.image2 %}{{ product.image2.url }}{% else %}{% static "img/no_image.png" %}{% endif %}"><img src="{% if product.image2 %}{{ product.image2.url }}{% else %}{% static "img/no_image.png" %}{% endif %}"></a>
                <a href="{% if product.image3 %}{{ product.image3.url }}{% else %}{% static "img/no_image.png" %}{% endif %}"><img src="{% if product.image3 %}{{ product.image3.url }}{% else %}{% static "img/no_image.png" %}{% endif %}"></a>
                <a href="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}"><img class="mainImg" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}"></a>
            </div>
      
        </div>
      
        <div class="discription pd">

        <h1 class="product">{{ product.name }}</h1>
        <p class="price">${{ product.price }}</p>
        <h2><a class="category" href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
     
<form action="{% url "cart:cart_add" product.id %}" method="post">
   <div class="cart-proudct">{{ cart_product_form }}</div>
    {% csrf_token %}
    <input class="btn-add" type="submit" value="Add to cart">
</form>
        <div class="description__subtitle" >{{ product.description }}</div>
    </div>
</div>
</div>

{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
UZARTISAN
{% endblock %}
{% block content %}


<div class="container">
    <div class="row">
        <div class="col-xl-12 col-md-12 col-lg-12 col-12">
            <div class="slider">
                <div class="slider__inner">
                    <img src="{% static "img/slider1.jpg" %}" alt="">
                    <img src="{% static "img/slider2.jpg" %}" alt="">
                    <img src="{% static "img/slider1.jpg" %}" alt="">
        
                </div>
                <div class="slider__btns">
                    <button class="btn btn-left"><i class="fa fa-arrow-left" aria-hidden="true"></i></button>
                    <button class="btn btn-right"><i class="fa fa-arrow-right" aria-hidden="true"></i></button>
                </div>
            </div>
            <ul class="indicators">
                <li class="active" data-slide-to="0">1</li>
                <li data-slide-to="1">2</li>
                <li data-slide-to="2">3</li>
            </ul>
        </div>
    </div>
</div>




<section class="products pd" id="shop">
    <div class="container products__container">
        <div class="row">
            <div class="col-xl-6 plates">
                    <h1><a href="plates/"  class="products__title">PLATES</a></h1>
                    <h1><a href="products/"  class="products__title mobile">PRODUCTS</a></h1>
                    <img src="{% static "img/plates.png" %}" alt="" width="100%">
            </div>
            <div class="col-xl-3 plates">
                <h1><a href="knives/" class="products__title knives">KNIVES</a></h1>
                <img class="tile" src="{% static "img/knives-1.png" %}" alt="">
                <h1><a href="products/"  class="products__title teapot">TEAPOT</a></h1>
                <img class="tile" src="{% static "img/teapot.png" %}" alt="">
            </div>
            <div class="col-xl-3 plates">
                <h1><a href="plates/"  class="products__title plates__title">PLATES</a></h1>
                <img class="tile" src="{% static "img/plates-1.png" %}" alt="" >
                <h1><a href="knives/"  class="products__title knives-2">KNIVES</a></h1>
                <img class="tile" src="{% static "img/knives.png" %}" alt="">
                
            </div>
         
        </div>
    </div>
</section>

<section class="about" id="about">
    <div class="container about__container">
        <div class="row">
            <div class="col-xl-12">
                <h1 class="about__title">ABOUT</h1>
                <p class="about__subtitle">We are small team</p>
                <p class="about__subtitle">Who are</p>
                <p class="about__subtitle">try to support local artisans in Uzbekistan.</p>
                <p class="about__subtitle">Our mission is show to people around world how handmade product are might beautiful</p>
            </div>
        </div>
    </div>
</section>

<section class="process pd" id="process">
    <div class="container process__container">

        <div class="row">
            <h1 class="process__title">PROCESS</h1>
            <div class="col-xl-6">
                <iframe width="100%" height="400" src="https://www.youtube.com/embed/tDRyS6wokSM" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
            <div class="col-xl-6">
                <iframe width="100%" height="400" src="https://www.youtube.com/embed/tDRyS6wokSM" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
            <div class="col-xl-6">
                <iframe width="100%" height="400" src="https://www.youtube.com/embed/tDRyS6wokSM" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
            <div class="col-xl-6">
                <iframe width="100%" height="400" src="https://www.youtube.com/embed/tDRyS6wokSM" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
            
            
            
        </div>
    </div>
</section>

    <!-- <div id="sidebar">
        <h3>Categories</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url "shop:product_list" %}">All</a>
            </li>
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">
        <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
        <div class="all">
           {% for product in products %}
        
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                </a>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
                ${{ product.price }}
            </div>
      
        {% endfor %}
    </div>
    </div> -->


{% endblock %}

shop/templates/shop/product/mainlist.html
{% extends "shop/base.html" %}
{% load static %}
{% block content %}

<div class="container mainlist">
    <div class="filter">
        <div class="container filter__container">
            <div class="row">
                <div class="filter__product">
                    <span class="filter__label">LOOKING FOR:</span>
                    <span class="filter__group">
                        ALL THE GOODS...
                        <div class="filter__option">
                            <a href="{% url "shop:product_list" %}"> <span data-products="card">  <li class="option" {% if not category %}class="selected"{% endif %}>
                               All
                            </li></span></a>
                            {% for c in categories %} <a href="{{ c.get_absolute_url }}">  <span data-products="platesShow" >
                                <li class="option" {% if category.slug == c.slug %}class="selected"{% endif %}>
                                   {{ c.name }}</span>
                                </li></a> 
                            {% endfor %}</a>
                       
                        </div>
                    </span>
               
                </div>
            </div>
        </div>
    </div>
<div id="sidebar">
    

    <ul>
      
        
     
       
    </ul>
</div>
<div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>

    <div class="all">
        <div class="row">
       {% for product in products %}
       <div class="col-xl-3 col-md-6 col-lg-6 test card knivesShow">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="" width="100%" >
        <div class="text">
        <div class="prodContent__title"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></div>
        <div class="prodContent__price">${{ product.price }}</div>
    </div>
    </div>
    
        <!-- <div class="item">
            <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
            </a>
            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
            ${{ product.price }}
        </div> -->
  
    {% endfor %}
    <!-- <div class="col-xl-3 test card knivesShow">
        <img src="img/knives-1.png" alt="" width="100%">
        <div class="text">
        <div class="prodContent__title">Machinist leather apron</div>
        <div class="prodContent__price">$280.00</div>
    </div> -->


</div>
</div>
</div>

</div>


<script src="{% static "js/products.js" %}"></script>
{% endblock %}